[package]
name = "keycloak"
version = "10.0.1"
authors = ["Alexander Korolev <kilork@yandex.ru>"]
edition = "2018"
categories = ["api-bindings", "asynchronous"]
description = """
Keycloak Admin REST API.
"""
homepage = "https://github.com/kilork/keycloak"
keywords = ["api", "async", "keycloak", "rest"]
license = "Unlicense OR MIT"
readme = "README.md"
repository = "https://github.com/kilork/keycloak"

[dependencies]
reqwest = { version = "0.10", features = [ "json" ] }
serde_json = "1"
serde = { version = "1", features = [ "derive" ] }

[dev-dependencies]
tokio = { version = "0.2", features = [ "full" ] }
scraper = "0.12"
heck = "0.3"
structopt = "0.3"
